### ISSUE TITLE
Keep-a-changelog produces non-compliant Markdown

### ISSUE THREAD

**Issue by jerusdp** [napalmpapalam/keep-a-changelog-rs#3]
**Description**
The Markdown produced when saved to a file is not compliant to the Markdown standard and does not pass Markdownlint. This means that when keep-a-changelog is used to edit a compliant file that file becomes non-compliant.

**Example**
Assuming that the keep-a-changelog change log is produced using keep-a-changing (in good dog-fooding tradition) it is an example as this file does not pass Markdownlint.

**Expected behavior**
That the markdown produced passes Markdownlint.

**Actual behavior**
It produces markdown that does not pass Markdownlint. 

**Environment**
 - OS: Linux
 - Rust version: 1.78.0
 - Project version: 0.1.2

**Additional context**
No additional context

**Comment by napalmpapalam** [comment]
Published under the [[0.1.3]](https://crates.io/crates/keep-a-changelog/0.1.3) version
